/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 5.27.0
 * source: opentelemetry/proto/resource/v1/resource.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as dependency_1 from '../../common/v1/common';
import * as pb_1 from 'google-protobuf';
export namespace opentelemetry.proto.resource.v1 {
    export class Resource extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(
            data?:
                | any[]
                | {
                      attributes?: dependency_1.opentelemetry.proto.common.v1.KeyValue[];
                      dropped_attributes_count?: number;
                      entity_refs?: dependency_1.opentelemetry.proto.common.v1.EntityRef[];
                  },
        ) {
            super();
            pb_1.Message.initialize(
                this,
                Array.isArray(data) ? data : [],
                0,
                -1,
                [1, 3],
                this.#one_of_decls,
            );
            if (!Array.isArray(data) && typeof data == 'object') {
                if ('attributes' in data && data.attributes != undefined) {
                    this.attributes = data.attributes;
                }
                if (
                    'dropped_attributes_count' in data &&
                    data.dropped_attributes_count != undefined
                ) {
                    this.dropped_attributes_count =
                        data.dropped_attributes_count;
                }
                if ('entity_refs' in data && data.entity_refs != undefined) {
                    this.entity_refs = data.entity_refs;
                }
            }
        }
        get attributes() {
            return pb_1.Message.getRepeatedWrapperField(
                this,
                dependency_1.opentelemetry.proto.common.v1.KeyValue,
                1,
            ) as dependency_1.opentelemetry.proto.common.v1.KeyValue[];
        }
        set attributes(
            value: dependency_1.opentelemetry.proto.common.v1.KeyValue[],
        ) {
            pb_1.Message.setRepeatedWrapperField(this, 1, value);
        }
        get dropped_attributes_count() {
            return pb_1.Message.getFieldWithDefault(this, 2, 0) as number;
        }
        set dropped_attributes_count(value: number) {
            pb_1.Message.setField(this, 2, value);
        }
        get entity_refs() {
            return pb_1.Message.getRepeatedWrapperField(
                this,
                dependency_1.opentelemetry.proto.common.v1.EntityRef,
                3,
            ) as dependency_1.opentelemetry.proto.common.v1.EntityRef[];
        }
        set entity_refs(
            value: dependency_1.opentelemetry.proto.common.v1.EntityRef[],
        ) {
            pb_1.Message.setRepeatedWrapperField(this, 3, value);
        }
        static fromObject(data: {
            attributes?: ReturnType<
                typeof dependency_1.opentelemetry.proto.common.v1.KeyValue.prototype.toObject
            >[];
            dropped_attributes_count?: number;
            entity_refs?: ReturnType<
                typeof dependency_1.opentelemetry.proto.common.v1.EntityRef.prototype.toObject
            >[];
        }): Resource {
            const message = new Resource({});
            if (data.attributes != null) {
                message.attributes = data.attributes.map((item) =>
                    dependency_1.opentelemetry.proto.common.v1.KeyValue.fromObject(
                        item,
                    ),
                );
            }
            if (data.dropped_attributes_count != null) {
                message.dropped_attributes_count =
                    data.dropped_attributes_count;
            }
            if (data.entity_refs != null) {
                message.entity_refs = data.entity_refs.map((item) =>
                    dependency_1.opentelemetry.proto.common.v1.EntityRef.fromObject(
                        item,
                    ),
                );
            }
            return message;
        }
        toObject() {
            const data: {
                attributes?: ReturnType<
                    typeof dependency_1.opentelemetry.proto.common.v1.KeyValue.prototype.toObject
                >[];
                dropped_attributes_count?: number;
                entity_refs?: ReturnType<
                    typeof dependency_1.opentelemetry.proto.common.v1.EntityRef.prototype.toObject
                >[];
            } = {};
            if (this.attributes != null) {
                data.attributes = this.attributes.map(
                    (
                        item: dependency_1.opentelemetry.proto.common.v1.KeyValue,
                    ) => item.toObject(),
                );
            }
            if (this.dropped_attributes_count != null) {
                data.dropped_attributes_count = this.dropped_attributes_count;
            }
            if (this.entity_refs != null) {
                data.entity_refs = this.entity_refs.map(
                    (
                        item: dependency_1.opentelemetry.proto.common.v1.EntityRef,
                    ) => item.toObject(),
                );
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.attributes.length)
                writer.writeRepeatedMessage(
                    1,
                    this.attributes,
                    (
                        item: dependency_1.opentelemetry.proto.common.v1.KeyValue,
                    ) => item.serialize(writer),
                );
            if (this.dropped_attributes_count != 0)
                writer.writeUint32(2, this.dropped_attributes_count);
            if (this.entity_refs.length)
                writer.writeRepeatedMessage(
                    3,
                    this.entity_refs,
                    (
                        item: dependency_1.opentelemetry.proto.common.v1.EntityRef,
                    ) => item.serialize(writer),
                );
            if (!w) return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): Resource {
            const reader =
                    bytes instanceof pb_1.BinaryReader
                        ? bytes
                        : new pb_1.BinaryReader(bytes),
                message = new Resource();
            while (reader.nextField()) {
                if (reader.isEndGroup()) break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        reader.readMessage(message.attributes, () =>
                            pb_1.Message.addToRepeatedWrapperField(
                                message,
                                1,
                                dependency_1.opentelemetry.proto.common.v1.KeyValue.deserialize(
                                    reader,
                                ),
                                dependency_1.opentelemetry.proto.common.v1
                                    .KeyValue,
                            ),
                        );
                        break;
                    case 2:
                        message.dropped_attributes_count = reader.readUint32();
                        break;
                    case 3:
                        reader.readMessage(message.entity_refs, () =>
                            pb_1.Message.addToRepeatedWrapperField(
                                message,
                                3,
                                dependency_1.opentelemetry.proto.common.v1.EntityRef.deserialize(
                                    reader,
                                ),
                                dependency_1.opentelemetry.proto.common.v1
                                    .EntityRef,
                            ),
                        );
                        break;
                    default:
                        reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): Resource {
            return Resource.deserialize(bytes);
        }
    }
}
